spring:
  application:
    name: user-service
  profiles:
    active: dev  #default profile


  #it's for NoHandlerFoundException (without - doesn't work)
  web:
    resources:
      add-mappings: false


  #for avoiding Open-In-View warnings:
  jpa:
    open-in-view: false

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
#        spring.json.use.type.headers: false

jwt:
  auth-secret: ${JWT_AUTH_SECRET}
  game-secret: ${JWT_GAME_SECRET}
  system-secret: ${JWT_SYSTEM_SECRET}

game-service:
  base-url: ${GAME_SERVICE_BASE_URL}

money-service:
  money-url: ${MONEY_SERVICE_URL}


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never
