spring:
  application:
    name: user-service
  profiles:
    active: dev  #default profile

jwt:
  auth-secret: ${JWT_AUTH_SECRET}
  game-secret: ${JWT_GAME_SECRET}
  system-secret: ${JWT_SYSTEM_SECRET}

game-service:
  base-url: ${GAME_SERVICE_BASE_URL}