package com.evofun.userservice.common.error;

public enum ErrorCode {
    VALIDATION_ERROR,
    AUTHORIZATION,
    GAME_RULE_VIOLATION,
    ALREADY_EXISTS,
    BAD_CREDENTIALS,
    SYSTEM_ERROR,
    USER_NOT_FOUND,
    INVALID_REQUEST_FORMAT,
    METHOD_NOT_SUPPORTED,
    UNKNOWN_ERROR,

    RESOURCE_NOT_FOUND,
    INVALID_TOKEN,
    FORBIDDEN,
    USERNAME_NOT_FOUND,
    INVALID_JSON_FORMAT,
    SERVICE_UNAVAILABLE
}